# Generated by Django 5.2.7 on 2025-10-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dificultades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'dificultades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=5)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaIngredients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'receta_ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaNutrition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('value_num', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'receta_nutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaRelated',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo', models.CharField(blank=True, max_length=50, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'receta_related',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.IntegerField(blank=True, null=True)),
                ('tiempo_prep', models.IntegerField(blank=True, null=True)),
                ('tiempo_coc', models.IntegerField(blank=True, null=True)),
                ('publicada', models.BooleanField()),
                ('image_url', models.CharField(blank=True, max_length=600, null=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'recetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaSteps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'receta_steps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaTips',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'receta_tips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('creado_en', models.DateTimeField()),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuarios')),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaTags',
            fields=[
                ('receta', models.ForeignKey(db_column='receta_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.recetas')),
            ],
            options={
                'db_table': 'receta_tags',
                'managed': False,
            },
        ),
    ]
